# GitHub actions workflow for SimutransPakManager
name: Build binaries
on:
  push:
    tags:
      - v*
      - ci/*
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: pip install requests cabarchive pyinstaller
      - name: Build binary
        run: |
          pyinstaller --onefile --name SimutransPakManager src/main.py
          chmod +x dist/SimutransPakManager
      - name: Zip binary
        run: zip -jX dist/SimutransPakManager.zip dist/SimutransPakManager
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimutransPakManager-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/SimutransPakManager.zip
