# GitHub actions workflow for SimutransPakManager
name: Build mac binaries
on:
  push:
    tags:
      - v*
      - ci/*
jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: pip install requests cabarchive beautifulsoup4 pyinstaller
      - name: Build binary
        run: |
          pyinstaller --onefile --name SimutransPakManager src/main.py
          chmod +x dist/SimutransPakManager
      - name: Zip binary
        run: zip -jX SimutransPakManager.zip dist/SimutransPakManager
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimutransPakManager-macos-${{ matrix.arch }}
          path: SimutransPakManager.zip
